# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_viewer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13remote_viewer.proto\x12\ronsite.viewer\"2\n\x06\x41\x63tion\x12\x10\n\x08steering\x18\x01 \x01(\x02\x12\x16\n\x0ethrottle_brake\x18\x02 \x01(\x02\"l\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x10\n\x08\x63hannels\x18\x04 \x01(\r\x12\x0e\n\x06\x66ormat\x18\x05 \x01(\t\x12\x14\n\x0ctimestamp_us\x18\x06 \x01(\x03\x32O\n\x13OnsiteViewerService\x12\x38\n\tSendImage\x12\x14.onsite.viewer.Image\x1a\x15.onsite.viewer.Actionb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'remote_viewer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTION._serialized_start=38
  _ACTION._serialized_end=88
  _IMAGE._serialized_start=90
  _IMAGE._serialized_end=198
  _ONSITEVIEWERSERVICE._serialized_start=200
  _ONSITEVIEWERSERVICE._serialized_end=279
# @@protoc_insertion_point(module_scope)
