# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chassis/proto/chassis_enums.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!chassis/proto/chassis_enums.proto\x12\x14vts.protocol.chassis*b\n\x07MsgType\x12\x14\n\x10VEHICLE_REGISTER\x10\x00\x12\x16\n\x12VEHICLE_UNREGISTER\x10\x01\x12\x13\n\x0fVEHICLE_CONTROL\x10\x02\x12\x14\n\x10VEHICLE_FEEDBACK\x10\x03*Y\n\x0b\x44rivingMode\x12\x07\n\x03OFF\x10\x00\x12\n\n\x06MANUAL\x10\x01\x12\x16\n\x12\x41UTONOMOUS_DRIVING\x10\x02\x12\t\n\x05\x46\x41ULT\x10\x03\x12\x12\n\x0eREMOTE_DRIVING\x10\x04*]\n\x0cVehicleError\x12\x06\n\x02OK\x10\x00\x12\x16\n\x12VEHICLE_REGISTERED\x10\x01\x12\x16\n\x12TESTCASE_NOT_READY\x10\x02\x12\x15\n\x11NO_MAP_FILE_FOUND\x10\x03*U\n\x13SteeringControlMode\x12\x1e\n\x1aTARGET_STEERING_ANGLE_MODE\x10\x00\x12\x1e\n\x1a\x41\x43TUAL_STEERING_ANGLE_MODE\x10\x01*@\n\x0fGearControlMode\x12\x17\n\x13\x41UTOMATIC_GEAR_MODE\x10\x00\x12\x14\n\x10MANUAL_GEAR_MODE\x10\x01*Z\n\x12\x44rivingControlMode\x12!\n\x1dTARGET_ACCELERATOR_PEDAL_MODE\x10\x00\x12!\n\x1d\x41\x43TUAL_ACCELERATOR_PEDAL_MODE\x10\x01*L\n\x10\x42rakeControlMode\x12\x1b\n\x17TARGET_BRAKE_PEDAL_MODE\x10\x00\x12\x1b\n\x17\x41\x43TUAL_BRAKE_PEDAL_MODE\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chassis.proto.chassis_enums_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MSGTYPE._serialized_start=59
  _MSGTYPE._serialized_end=157
  _DRIVINGMODE._serialized_start=159
  _DRIVINGMODE._serialized_end=248
  _VEHICLEERROR._serialized_start=250
  _VEHICLEERROR._serialized_end=343
  _STEERINGCONTROLMODE._serialized_start=345
  _STEERINGCONTROLMODE._serialized_end=430
  _GEARCONTROLMODE._serialized_start=432
  _GEARCONTROLMODE._serialized_end=496
  _DRIVINGCONTROLMODE._serialized_start=498
  _DRIVINGCONTROLMODE._serialized_end=588
  _BRAKECONTROLMODE._serialized_start=590
  _BRAKECONTROLMODE._serialized_end=666
# @@protoc_insertion_point(module_scope)
