import copy
import logging
import uuid
import torch
import gymnasium as gym
import numpy as np
from metadrive.base_class.configurable import Configurable
from metadrive.base_class.randomizable import Randomizable


class BasePolicy(Randomizable, Configurable):
    DEBUG_MARK_COLOR = (255, 255, 255, 255)
    DEBUG_MARK_MODEL = None
    SYNC_DEBUG_MARK_POS_TASK_NAME = "policy_mark"

    def __init__(self, step_manager, config=None):
        Configurable.__init__(self, config)
        Randomizable.__init__(self, 0)
        self.step_manager = step_manager
        self.action_info = dict()

    def reset(self, controller, seed, state, init_state, **kwargs):
        self.controller = controller
        self.seed(seed)

        timestamp_list = sorted(state.keys())
        self.spawn_timestamp = timestamp_list[0]

        self.trajectory = state
        self.destination = init_state['destination']
        self.static = sum([np.linalg.norm(traj['velocity']) for traj in self.trajectory.values()]) / len(self.trajectory) < 0.1

    def act(self, *args, **kwargs):
        """
        Return an action vector consisting of two element: [steering, throttle/brake]. Runtime information generated by
        the policy can be written to self.action_info, which will be retrieved and shown in info dict automatically.
        """
        pass
    
    @property
    def is_arrive(self):
        p = self.controller.position
        dest = self.destination
        return (p[0] - dest[0])**2 + (p[1] - dest[1])**2 < 4 and not self.static
    
    @property
    def is_spawned(self):
        return self.step_manager.current_timestamp >= self.spawn_timestamp

    @property
    def is_in_trajectory(self):
        ego_position = self.controller.position
        ego_position = torch.tensor([ego_position[0], ego_position[1]], dtype=torch.float32)

        states = self.trajectory.values()
        expert_positions = torch.stack([torch.tensor(state['position'][:2]).float() for state in states])

        distances = torch.norm(expert_positions - ego_position.unsqueeze(0), dim=1)
        min_distance = torch.min(distances).item()
        road_threshold = 5.0
        return min_distance < road_threshold
    
    def get_action_info(self):
        """
        Get current action info for env.step() retrieve
        """
        return copy.deepcopy(self.action_info)

    def destroy(self):
        """
        Destroy Base class
        """
        Configurable.destroy(self)
        Randomizable.destroy(self)

    @property
    def name(self):
        return self.__class__.__name__

    def __repr__(self):
        return self.name

    @classmethod
    def get_input_space(cls):
        """
        It defines the input space of this class of policy. This will be the action space for the agent.
        """
        return gym.spaces.Box(-1.0, 1.0, shape=(2, ), dtype=np.float32)

    def get_state(self):
        return self.get_action_info()
