# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import render_pb2 as render__pb2


class RenderServiceStub(object):
    """Render service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Render = channel.unary_unary(
                '/nurec.render.RenderService/Render',
                request_serializer=render__pb2.RenderRequest.SerializeToString,
                response_deserializer=render__pb2.RenderResponse.FromString,
                )
        self.SetTrafficPose = channel.unary_unary(
                '/nurec.render.RenderService/SetTrafficPose',
                request_serializer=render__pb2.TrafficPoseRequest.SerializeToString,
                response_deserializer=render__pb2.TrafficPoseResponse.FromString,
                )
        self.LoadModel = channel.unary_unary(
                '/nurec.render.RenderService/LoadModel',
                request_serializer=render__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=render__pb2.LoadModelResponse.FromString,
                )


class RenderServiceServicer(object):
    """Render service definition
    """

    def Render(self, request, context):
        """Render a single camera view
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTrafficPose(self, request, context):
        """Update traffic pose override for rendering
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Load the checkpoint model for rendering
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RenderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Render': grpc.unary_unary_rpc_method_handler(
                    servicer.Render,
                    request_deserializer=render__pb2.RenderRequest.FromString,
                    response_serializer=render__pb2.RenderResponse.SerializeToString,
            ),
            'SetTrafficPose': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTrafficPose,
                    request_deserializer=render__pb2.TrafficPoseRequest.FromString,
                    response_serializer=render__pb2.TrafficPoseResponse.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=render__pb2.LoadModelRequest.FromString,
                    response_serializer=render__pb2.LoadModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nurec.render.RenderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RenderService(object):
    """Render service definition
    """

    @staticmethod
    def Render(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nurec.render.RenderService/Render',
            render__pb2.RenderRequest.SerializeToString,
            render__pb2.RenderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTrafficPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nurec.render.RenderService/SetTrafficPose',
            render__pb2.TrafficPoseRequest.SerializeToString,
            render__pb2.TrafficPoseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nurec.render.RenderService/LoadModel',
            render__pb2.LoadModelRequest.SerializeToString,
            render__pb2.LoadModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
